CREATE TABLE ROLES
(
    id SERIAL PRIMARY KEY NOT NULL UNIQUE,
    Name CHARACTER VARYING (55) NOT NULL UNIQUE
);

INSERT INTO ROLES (id, Name) VALUES (1, 'admin');
INSERT INTO ROLES (id, Name) VALUES (2, 'user');