name: JavaCI

on:
  push:
    branches:
      - new_tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version:

      - name: Build and Test with Maven
        run: mvn -B clean verify

      - name: Complete job
        run: echo "Job completed successfully"
