name: JavaCI

on:
  push:
    branches:
      - new_tests

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_DB: screener
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: '19'

      - name: Build and Test with Maven
        run: mvn -B clean verify

      - name: Complete job
        run: echo "Job completed successfully"
